version: '3'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    tty: true
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent volume for RabbitMQ data
    environment:
      RABBITMQ_DEFAULT_USER: 'test'  # Set default RabbitMQ user
      RABBITMQ_DEFAULT_PASS: 'password'  # Set default RabbitMQ password
    ports:
        - "15672:15672"
        - "5672:5672"

  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  rabbitmq_data:
    driver: local
  mysql_data:
    driver: local